server:
  http:
    addr: 0.0.0.0:8023
    timeout: 2s
  grpc:
    addr: 0.0.0.0:9023
    timeout: 2s
data:
  database:
    driver: mysql
    source: myuser:mypassword@tcp(mysql:3306)/chatify?parseTime=true
  redis:
    network: tcp
    addr: redis:6379
    read_timeout: 2s
    write_timeout: 2s
  etcd:
    endpoints: ["etcd:2379"]
    dial_timeout: 2s
    username: ""
    password: ""
# 监控配置统一放在monitoring下
monitoring:
  service_name: offline-service
  tracing:
    sampler: 1.0
    exporter: jaeger
    jaeger:
      endpoint: 172.26.238.249:32750
  logging:
    level: debug
    format: json
    output: stdout
  metrics:
    prometheus:
      endpoint: :2112
      timeout: 10s


