server:
  http:
    addr: 0.0.0.0:8033
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9033
    timeout: 1s
data:
  database:
    driver: mysql
    source: myuser:mypassword@tcp(localhost:13306)/chatify?parseTime=true
  redis:
    network: tcp
    addr: localhost:16379
    read_timeout: 1s
    write_timeout: 1s
  etcd:
    endpoints: ["localhost:22379"]
    dial_timeout: 1s
    username: ""
    password: ""
  kafka:
    brokers: ["localhost:19092"]
    group_id: chatify
    retry_count: 3
    timeout: 3s
client:
  access_client: 
    addr: "access"
    timeout: 1s
  offline_client: 
    addr: "offline"
    timeout: 1s
# 监控配置统一放在monitoring下
monitoring:
  service_name: push-service
  tracing:
    sampler: 1.0
    exporter: jaeger
    jaeger:
      endpoint: 172.26.238.249:32750
  logging:
    level: debug
    format: json
    output: stdout
  metrics:
    prometheus:
      endpoint: :2112
      timeout: 10s
