server:
  http:
    network: tcp
    addr: 0.0.0.0:8080
    timeout: 1s
  grpc:
    network: tcp
    addr: 0.0.0.0:9090
    timeout: 1s

data:
  database:
    driver: mysql
    source: myuser:mypassword@tcp(localhost:13306)/chatify?parseTime=true
  redis:
    network: tcp
    addr: localhost:16379
    read_timeout: 1s
    write_timeout: 1s

auth:
  access_token_ttl: 600        # 10分钟
  refresh_token_ttl: 604800     # 7天

# 监控配置统一放在monitoring下
monitoring:
  service_name: auth-service
  tracing:
    sampler: 1.0
    exporter: jaeger
    jaeger:
      endpoint: 172.26.238.249:32750
  logging:
    level: debug
    format: json
    output: stdout
  metrics:
    prometheus:
      endpoint: :2112
      timeout: 10s